import random
words = ['python', 'javascript', 'java', 'automation', 'pytest', 'guvi', 'selenium']
original_word = random.choice(words)
print(f'Original Word generated by the system is: {original_word}')
mid = len(original_word) // 2
scrambled_word = original_word[mid:]+original_word[:mid]
correct_guess = False
while not correct_guess:
    guess = input("What is your guess word: ").lower()
    if guess == original_word:
        print("Your guess is correct")
        correct_guess=True
    else:
        print("Your guess is wrong")